import { colors } from "./colors";

export interface Category {
  type: "category";
  id: string;
  slug: string;
  title: string;
  color: (typeof colors)[keyof typeof colors];
  cover: string;
}

export const categories: Category[] = [
  {
    type: "category",
    id: "adoracio",
    slug: "adoracio",
    title: "Adoració",
    color: colors.yellow,
    cover: "https://picsum.photos/seed/adoracio/400/300",
  },
  {
    type: "category",
    id: "animacio",
    slug: "animacio",
    title: "Animació",
    color: colors.red,
    cover: "https://picsum.photos/seed/animacio/400/300",
  },
  {
    type: "category",
    id: "esperit",
    slug: "esperit",
    title: "Esperit",
    color: colors.yellow,
    cover: "https://picsum.photos/seed/esperit/400/300",
  },
  {
    type: "category",
    id: "fe",
    slug: "fe",
    title: "Fe",
    color: colors.red,
    cover: "https://picsum.photos/seed/fe/400/300",
  },
  {
    type: "category",
    id: "gracies",
    slug: "gracies",
    title: "Gràcies",
    color: colors.yellow,
    cover: "https://picsum.photos/seed/gracies/400/300",
  },
  {
    type: "category",
    id: "guariment",
    slug: "guariment",
    title: "Guariment",
    color: colors.red,
    cover: "https://picsum.photos/seed/guariment/400/300",
  },
  {
    type: "category",
    id: "invitatori",
    slug: "invitatori",
    title: "Invitatori",
    color: colors.red,
    cover: "https://picsum.photos/seed/invitatori/400/300",
  },
  {
    type: "category",
    id: "lloanca",
    slug: "lloanca",
    title: "Lloança",
    color: colors.red,
    cover: "https://picsum.photos/seed/lloanca/400/300",
  },
  {
    type: "category",
    id: "missa",
    slug: "missa",
    title: "Missa",
    color: colors.red,
    cover: "https://picsum.photos/seed/missa/400/300",
  },
  {
    type: "category",
    id: "missio",
    slug: "missio",
    title: "Missió",
    color: colors.red,
    cover: "https://picsum.photos/seed/missio/400/300",
  },
  {
    type: "category",
    id: "poupurri",
    slug: "poupurri",
    title: "Poupurri",
    color: colors.red,
    cover: "https://picsum.photos/seed/poupurri/400/300",
  },
  {
    type: "category",
    id: "resurreccio",
    slug: "resurreccio",
    title: "Resurrecció",
    color: colors.red,
    cover: "https://picsum.photos/seed/resurreccio/400/300",
  },
];

const homeCategoriesList = ["Fe", "Animació", "Guariment", "Esperit"];

export const homeCategories = categories.filter((category) =>
  homeCategoriesList.includes(category.title)
);

// export const moreCategories = categories.map((item) => ({
//   ...item,
//   slug: item.slug + "_more",
// }));

// export const sidebarCategories = categories.map((item) => ({
//   ...item,
//   slug: item.slug + "_side",
// }));

// export const allCategories = [
//   ...categories,
//   ...moreCategories,
//   ...sidebarCategories,
// ];

export interface Song {
  type: "song";
  id: string;
  slug: string;
  src: string;
  categoriesId: string[];
  title: string;
  image: string;
  artists: string[];
}

export const songs: Song[] = [
  {
    type: "song",
    id: "vine-sant-esperit",
    slug: "vine-sant-esperit",
    src: "/music/vine-sant-esperit.mp3",
    categoriesId: ["esperit"],
    title: "Vine Sant Esperit",
    image: `https://picsum.photos/seed/vine-sant-esperit/400/300`,
    artists: ["Marcos Barrientos"],
  },
  {
    type: "song",
    id: "vine-pare-do-de-vida",
    slug: "vine-pare-do-de-vida",
    src: "/music/vine-pare-do-de-vida.mp3",
    categoriesId: ["esperit"],
    title: "Vine Pare do de vida",
    image: `https://picsum.photos/seed/vine-pare-do-de-vida/400/300`,
    artists: ["Susana Mota Martín"],
  },
  {
    type: "song",
    id: "vine-a-coneixer-el-meu-salvador",
    slug: "vine-a-coneixer-el-meu-salvador",
    src: "/music/vine-a-coneixer-el-meu-salvador.mp3",
    categoriesId: ["poupurri"],
    title: "Vine a coneixer el meu Salvador",
    image: `https://picsum.photos/seed/vine-a-coneixer-el-meu-salvador/400/300`,
    artists: ["Desconegut"],
  },
  {
    type: "song",
    id: "transformam",
    slug: "transformam",
    src: "/music/transformam.mp3",
    categoriesId: ["guariment"],
    title: "Transforma'm",
    image: `https://picsum.photos/seed/transformam/400/300`,
    artists: ["Marcos Witt"],
  },
  {
    type: "song",
    id: "tot-es-pel-meu-crist",
    slug: "tot-es-pel-meu-crist",
    src: "/music/tot-es-pel-meu-crist.mp3",
    categoriesId: ["fe"],
    title: "Tot es pel meu Crist",
    image: `https://picsum.photos/seed/tot-es-pel-meu-crist/400/300`,
    artists: ["Marcos Barrientos"],
  },
  {
    type: "song",
    id: "tocare-lextrem-del-teu-vestit-guareixme-ara",
    slug: "tocare-lextrem-del-teu-vestit-guareixme-ara",
    src: "/music/tocare-lextrem-del-teu-vestit-guareixme-ara.mp3",
    categoriesId: ["guariment"],
    title: "Tocaré l'extrem del teu vestit - Guareix-me ara",
    image: `https://picsum.photos/seed/tocare-lextrem-del-teu-vestit-guareixme-ara/400/300`,
    artists: ["Marcelo Olima"],
  },
  {
    type: "song",
    id: "tinc-les-mans-plenes",
    slug: "tinc-les-mans-plenes",
    src: "/music/tinc-les-mans-plenes.mp3",
    categoriesId: ["animacio"],
    title: "Tinc les mans plenes",
    image: `https://picsum.photos/seed/tinc-les-mans-plenes/400/300`,
    artists: ["Desconegut"],
  },
  {
    type: "song",
    id: "senyor-portam-als-teus-atris",
    slug: "senyor-portam-als-teus-atris",
    src: "/music/senyor-portam-als-teus-atris.mp3",
    categoriesId: ["adoracio"],
    title: "Senyor, porta'm als teus atris",
    image: `https://picsum.photos/seed/senyor-portam-als-teus-atris/400/300`,
    artists: ["Desconegut"],
  },
  {
    type: "song",
    id: "senyor-meu-i-deu-meu-no-hi-ha-ningu-com-tu",
    slug: "senyor-meu-i-deu-meu-no-hi-ha-ningu-com-tu",
    src: "/music/senyor-meu-i-deu-meu-no-hi-ha-ningu-com-tu.mp3",
    categoriesId: ["lloanca"],
    title: "Senyormeu i Déu meu, no hi ha ningú com tu",
    image: `https://picsum.photos/seed/senyor-meu-i-deu-meu-no-hi-ha-ningu-com-tu/400/300`,
    artists: ["Darlene Zschech"],
  },
  {
    type: "song",
    id: "que-es-aixo-que-baixa",
    slug: "que-es-aixo-que-baixa",
    src: "/music/que-es-aixo-que-baixa.mp3",
    categoriesId: ["poupurri"],
    title: "Què és això que baixa",
    image: `https://picsum.photos/seed/que-es-aixo-que-baixa/400/300`,
    artists: ["Desconegut"],
  },
  {
    type: "song",
    id: "preparat-per-acollir",
    slug: "preparat-per-acollir",
    src: "/music/preparat-per-acollir.mp3",
    categoriesId: ["poupurri"],
    title: "Prepara't per acollir",
    image: `https://picsum.photos/seed/preparat-per-acollir/400/300`,
    artists: ["Desconegut"],
  },
  {
    type: "song",
    id: "oh-crist-senyor-meu-digne-es-el-teu-nom",
    slug: "oh-crist-senyor-meu-digne-es-el-teu-nom",
    src: "/music/oh-crist-senyor-meu-digne-es-el-teu-nom.mp3",
    categoriesId: ["fe"],
    title: "Oh, Crist Senyor meu digne és el teu nom",
    image: `https://picsum.photos/seed/oh-crist-senyor-meu-digne-es-el-teu-nom/400/300`,
    artists: ["Dennis Jernigan"],
  },
  {
    type: "song",
    id: "no-pot-estar-trist",
    slug: "no-pot-estar-trist",
    src: "/music/no-pot-estar-trist.mp3",
    categoriesId: ["animacio"],
    title: "No pot estar tirst",
    image: `https://picsum.photos/seed/no-pot-estar-trist/400/300`,
    artists: ["Amilkar Hernandez"],
  },
  {
    type: "song",
    id: "mireu-desperteu-al-nou-dia-ha-ressuscitat",
    slug: "mireu-desperteu-al-nou-dia-ha-ressuscitat",
    src: "/music/mireu-desperteu-al-nou-dia-ha-ressuscitat.mp3",
    categoriesId: ["resurreccio"],
    title: "Mireu desperteu al nou dia - Ha ressuscitat",
    image: `https://picsum.photos/seed/mireu-desperteu-al-nou-dia-ha-ressuscitat/400/300`,
    artists: ["Lázaro Iparraguirre"],
  },
  {
    type: "song",
    id: "lloem-tots-al-senyor",
    slug: "lloem-tots-al-senyor",
    src: "/music/lloem-tots-al-senyor.mp3",
    categoriesId: ["animacio"],
    title: "Lloem tots al Senyor",
    image: `https://picsum.photos/seed/lloem-tots-al-senyor/400/300`,
    artists: ["Paul Bolache"],
  },
  {
    type: "song",
    id: "lloanca-i-gloria-al-teu-nom",
    slug: "lloanca-i-gloria-al-teu-nom",
    src: "/music/lloanca-i-gloria-al-teu-nom.mp3",
    categoriesId: ["lloanca"],
    title: "Lloança i glòria al teu Nom",
    image: `https://picsum.photos/seed/lloança-i-gloria-al-teu-nom/400/300`,
    artists: ["C.d.Emmanuel - E. Baranger"],
  },
  {
    type: "song",
    id: "ell-es-rei-de-reis",
    slug: "ell-es-rei-de-reis",
    src: "/music/ell-es-rei-de-reis.mp3",
    categoriesId: ["lloanca"],
    title: "Ell és Rei de reis",
    image: `https://picsum.photos/seed/ell-es-rei-de-reis/400/300`,
    artists: ["Desconegut"],
  },
  {
    type: "song",
    id: "lloa-deu",
    slug: "lloa-deu",
    src: "/music/lloa-deu.mp3",
    categoriesId: ["lloanca"],
    title: "Lloa Déu",
    image: `https://picsum.photos/seed/lloa-deu/400/300`,
    artists: ["Henry Smith"],
  },
  {
    type: "song",
    id: "lesperit-del-senyor",
    slug: "lesperit-del-senyor",
    src: "/music/lesperit-del-senyor.mp3",
    categoriesId: ["esperit"],
    title: "L'Esperit del Senyor",
    image: `https://picsum.photos/seed/lesperit-del-senyor/400/300`,
    artists: ["J. Miquel Cubeles", "Antoni Torrelles", "Florenci Jové"],
  },
  {
    type: "song",
    id: "ja-esta-baixant",
    slug: "ja-esta-baixant",
    src: "/music/ja-esta-baixant.mp3",
    categoriesId: ["poupurri"],
    title: "Ja està baixant",
    image: `https://picsum.photos/seed/ja-esta-baixant/400/300`,
    artists: ["Desconegut"],
  },
  {
    type: "song",
    id: "hi-ha-una-promesa-a-la-biblia",
    slug: "hi-ha-una-promesa-a-la-biblia",
    src: "/music/hi-ha-una-promesa-a-la-biblia.mp3",
    categoriesId: ["poupurri"],
    title: "Hi ha una promesa a la Bíblia",
    image: `https://picsum.photos/seed/hi-ha-una-promesa-a-la-biblia/400/300`,
    artists: ["P. Lucas Casaert"],
  },
  {
    type: "song",
    id: "has-mudat-en-danses-els-meus-planys-i-oh-adonai",
    slug: "has-mudat-en-danses-els-meus-planys-i-oh-adonai",
    src: "/music/has-mudat-en-danses-els-meus-planys-i-oh-adonai.mp3",
    categoriesId: ["animacio"],
    title: "Has mudat en danses els meus planys i Oh, Adonai",
    image: `https://picsum.photos/seed/has-mudat-en-danses-els-meus-planys-i-oh-adonai/400/300`,
    artists: ["Marcos Witt"],
  },
  {
    type: "song",
    id: "gracies-et-donare",
    slug: "gracies-et-donare",
    src: "/music/gracies-et-donare.mp3",
    categoriesId: ["gracies"],
    title: "Gràcies et donaré",
    image: `https://picsum.photos/seed/gracies-et-donare/400/300`,
    artists: ["Desconegut"],
  },
  {
    type: "song",
    id: "flama-de-deu",
    slug: "flama-de-deu",
    src: "/music/flama-de-deu.mp3",
    categoriesId: ["esperit"],
    title: "Flama de Déu",
    image: `https://picsum.photos/seed/flama-de-deu/400/300`,
    artists: ["C.d.Emmanuel - J.M.Morin", "P. i V. Mugnier"],
  },
  {
    type: "song",
    id: "fixa-els-ulls-en-jesus",
    slug: "fixa-els-ulls-en-jesus",
    src: "/music/fixa-els-ulls-en-jesus.mp3",
    categoriesId: ["fe"],
    title: "Fixa els ulls en Jesús",
    image: `https://picsum.photos/seed/fixa-els-ulls-en-jesus/400/300`,
    artists: ["Helen Howarth Lemmel"],
  },
  {
    type: "song",
    id: "estimare-el-senyor-amb-tot-el-meu-cor",
    slug: "estimare-el-senyor-amb-tot-el-meu-cor",
    src: "/music/estimare-el-senyor-amb-tot-el-meu-cor.mp3",
    categoriesId: ["lloanca"],
    title: "Estimaré el Senyor amb tot el meu cor",
    image: `https://picsum.photos/seed/estimare-el-senyor-amb-tot-el-meu-cor/400/300`,
    artists: ["Claude Fraysse", "Alain Bergèsse"],
  },
  {
    type: "song",
    id: "entra-en-la-presencia-lloat-sigui-el-senyor-mix",
    slug: "entra-en-la-presencia-lloat-sigui-el-senyor-mix",
    src: "/music/entra-en-la-presencia-lloat-sigui-el-senyor-mix.mp3",
    categoriesId: ["adoracio"],
    title: "Entra en la presència - Lloat sigui el Senyor (Mix)",
    image: `https://picsum.photos/seed/"entra-en-la-presencia-lloat-sigui-el-senyor-mix"/400/300`,
    artists: ["Lynn Baird", "Bob Fitts"],
  },
  {
    type: "song",
    id: "encen-una-llum",
    slug: "encen-una-llum",
    src: "/music/encen-una-llum.mp3",
    categoriesId: ["missio"],
    title: "Encén una llum",
    image: `https://picsum.photos/seed/encen-una-llum/400/300`,
    artists: ["Marcos Witt"],
  },
  {
    type: "song",
    id: "enamoram-vull-els-meus-somnis-lliurarte",
    slug: "enamoram-vull-els-meus-somnis-lliurarte",
    src: "/music/enamoram-vull-els-meus-somnis-lliurarte.mp3",
    categoriesId: ["fe"],
    title: "Enamora'm - Vull els meus somnis lliurar-te",
    image: `https://picsum.photos/seed/enamoram-vull-els-meus-somnis-lliurarte/400/300`,
    artists: ["Abel Zavala"],
  },
  {
    type: "song",
    id: "en-presencia-del-meu-sant-senyor",
    slug: "en-presencia-del-meu-sant-senyor",
    src: "/music/en-presencia-del-meu-sant-senyor.mp3",
    categoriesId: ["adoracio"],
    title: "En presència del meu Sant Senyor",
    image: `https://picsum.photos/seed/en-presencia-del-meu-sant-senyor/400/300`,
    artists: ["Mark Altrogge"],
  },
  {
    type: "song",
    id: "el-meu-deu-es-viu",
    slug: "el-meu-deu-es-viu",
    src: "/music/el-meu-deu-es-viu.mp3",
    categoriesId: ["animacio"],
    title: "El meu Déu és viu",
    image: `https://picsum.photos/seed/el-meu-deu-es-viu/400/300`,
    artists: ["Francisco Palazón", "Martín Verde Barajas"],
  },
  {
    type: "song",
    id: "deu-fara-un-cami",
    slug: "deu-fara-un-cami",
    src: "/music/deu-fara-un-cami.mp3",
    categoriesId: ["fe"],
    title: "Déu farà un camí",
    image: `https://picsum.photos/seed/deu-fara-un-cami/400/300`,
    artists: ["Don Moen"],
  },
  {
    type: "song",
    id: "deu-es-aqui-amb-forca-i-gloria",
    slug: "deu-es-aqui-amb-forca-i-gloria",
    src: "/music/deu-es-aqui-amb-forca-i-gloria.mp3",
    categoriesId: ["lloanca"],
    title: "Déu és aquí amb força i glòria",
    image: `https://picsum.photos/seed/deu-es-aqui-amb-forca-i-gloria/400/300`,
    artists: ["Desconegut"],
  },
  {
    type: "song",
    id: "des-dels-limits-del-mon",
    slug: "des-dels-limits-del-mon",
    src: "/music/des-dels-limits-del-mon.mp3",
    categoriesId: ["lloanca"],
    title: "Des dels límits del món",
    image: `https://picsum.photos/seed/des-dels-limits-del-mon/400/300`,
    artists: ["Don Harris", "Gary Sadler"],
  },
  {
    type: "song",
    id: "crist-ha-ressuscitat",
    slug: "crist-ha-ressuscitat",
    src: "/music/crist-ha-ressuscitat.mp3",
    categoriesId: ["resurreccio"],
    title: "Crist ha ressuscitat",
    image: `https://picsum.photos/seed/crist-ha-ressuscitat/400/300`,
    artists: ["Traducció hebrea"],
  },
  {
    type: "song",
    id: "cos-de-jesus",
    slug: "cos-de-jesus",
    src: "/music/cos-de-jesus.mp3",
    categoriesId: ["adoracio", "missa"],
    title: "Cos de Jesús",
    image: `https://picsum.photos/seed/cos-de-jesus/400/300`,
    artists: ["C.d.Emmanuel - M. i M. F. Penhart"],
  },
  {
    type: "song",
    id: "canta-un-nou-cant-al-senyor-que-ressoni",
    slug: "canta-un-nou-cant-al-senyor-que-ressoni",
    src: "/music/canta-un-nou-cant-al-senyor-que-ressoni.mp3",
    categoriesId: ["invitatori"],
    title: "Canta un nou cant al Senyor que ressoni",
    image: `https://picsum.photos/seed/canta-un-nou-cant-al-senyor-que-ressoni/400/300`,
    artists: ["Dan Shutte"],
  },
  {
    type: "song",
    id: "beneiu-el-senyor",
    slug: "beneiu-el-senyor",
    src: "/music/beneiu-el-senyor.mp3",
    categoriesId: ["poupurri"],
    title: "Beneïu el Senyor",
    image: `https://picsum.photos/seed/beneiu-el-senyor/400/300`,
    artists: ["Bob Probert"],
  },
  {
    type: "song",
    id: "beneire-el-teu-nom-et-beneire",
    slug: "beneire-el-teu-nom-et-beneire",
    src: "/music/beneire-el-teu-nom-et-beneire.mp3",
    categoriesId: ["lloanca"],
    title: "Beneiré el teu nom - Et beneiré",
    image: `https://picsum.photos/seed/beneire-el-teu-nom-et-beneire/400/300`,
    artists: ["Matt Redman", "Betd Redman"],
  },
  {
    type: "song",
    id: "avui-el-senyor-mha-cridat",
    slug: "avui-el-senyor-mha-cridat",
    src: "/music/avui-el-senyor-mha-cridat.mp3",
    categoriesId: ["animacio"],
    title: "Avui el Senyor m'ha cridat",
    image: `https://picsum.photos/seed/avui-el-senyor-mha-cridat/400/300`,
    artists: ["Isaïes 49:1-26"],
  },
  {
    type: "song",
    id: "amb-la-joia-als-llavis",
    slug: "amb-la-joia-als-llavis",
    src: "/music/amb-la-joia-als-llavis.mp3",
    categoriesId: ["lloanca"],
    title: "Amb la joia als llavis",
    image: `https://picsum.photos/seed/amb-la-joia-als-llavis/400/300`,
    artists: ["C. E. Hauguel", "Salm 63 (62)"],
  },
  {
    type: "song",
    id: "alcat-radiant-jerusalem",
    slug: "alcat-radiant-jerusalem",
    src: "/music/alcat-radiant-jerusalem.mp3",
    categoriesId: ["lloanca"],
    title: "Alçat radiant - Jerusalem",
    image: `https://picsum.photos/seed/alcat-radiant-jerusalem/400/300`,
    artists: ["C.d.Emmanuel - J. M. Morin", "Isaïes 60"],
  },
  {
    type: "song",
    id: "alleluia-lloeu-deu-al-seu-santuari",
    slug: "alleluia-lloeu-deu-al-seu-santuari",
    src: "/music/alleluia-lloeu-deu-al-seu-santuari.mp3",
    categoriesId: ["lloanca"],
    title: "Al·leluia. Lloeu Déu al seu santuari",
    image: `https://picsum.photos/seed/alleluia-lloeu-deu-al-seu-santuari/400/300`,
    artists: ["A. Taulé", "Salm 150"],
  },
  {
    type: "song",
    id: "alleluia-ha-ressuscitat",
    slug: "alleluia-ha-ressuscitat",
    src: "/music/alleluia-ha-ressuscitat.mp3",
    categoriesId: ["resurreccio"],
    title: "Al·leluia, ha ressuscitat",
    image: `https://picsum.photos/seed/alleluia-ha-ressuscitat/400/300`,
    artists: ["Don Moen"],
  },
  {
    type: "song",
    id: "ah-si-sabes-ton-cor",
    slug: "ah-si-sabes-ton-cor",
    src: "/music/ah-si-sabes-ton-cor.mp3",
    categoriesId: ["fe"],
    title: "Ah, si sabes ton cor",
    image: `https://picsum.photos/seed/ah-si-sabes-ton-cor/400/300`,
    artists: ["GOCAM"],
  },
];

const homeSongsList = [
  "Vine Sant Esperit",
  "Vine Pare do de vida",
  "Vine a coneixer el meu Salvador",
  "Transforma'm",
];

export const homeSongs = songs.filter((song) =>
  homeSongsList.includes(song.title)
);
